### PR TITLE
Material icons broken  (Fixes #334)

### LINKED ISSUE #334: Material icons broken
#332 broke the material icons in the header and footer.

image

root cause: bdf7d23e9ab19b6285d432bdc0345114536abf64

### PR DESCRIPTION
**Pull request by davidstanke**
Fixes #334

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr335-draft-uda3kvct.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr335-l1ixhui4.web.app

**Comment by davidstanke** [comment]
Screenshot from Browserstack: 
image

**Review by nathenharvey — APPROVED** [review]
Reviewed in safari and chrome.  

👍

**Pull request merged**
