### PR TITLE
next round of core

### PR DESCRIPTION
**Pull request by davidstanke**

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr325-draft-ce9nq3mx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr325-3dyroqrn.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr325-draft-ce9nq3mx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr325-3dyroqrn.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr325-draft-ce9nq3mx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr325-3dyroqrn.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr325-draft-ce9nq3mx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr325-3dyroqrn.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr325-draft-ce9nq3mx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr325-3dyroqrn.web.app

**Comment by davidstanke** [comment]
This PR restructures the content files to prepare Core to move onto `/research`, including a redirect from `/core` to the new, WIP research page. It also adds information about Core to the FAQ.

**Review by swansama — APPROVED** [review]
LGTM :)

**Pull request merged**
