### PR TITLE
Supporting PR Commit edits (Issue #333)

### LINKED ISSUE #333: Simplify PR preview links
Currently, when a PR is opened, the CI pipelines append comments to the PR: "Preview this PR [....] at [...]"

...it's a bit messy b/c there are separate comments for "draft" and "published" versions, and also (more irritatingly) because it posts a new comment every time new commits are added to the PR. This makes for long threads on the "Conversation" view of many PRs.

Could we:
* Post only one comment, containing both the "draft" and "published" preview URLs?
* On subsequent commits, update the existing comment, or delete-and-replace it, so that there's only one preview message per PR? (Note that in the current behavior, the links are always the same, since Firebase reuses the same Preview Channel for each new build of the same PR. It's rather redundant.)

### PR DESCRIPTION
**Pull request by jessegduke**
Fixes #333

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr345-draft-8ywyqfsj.web.app
Preview this PR [published content only] at https://doradotdev--pr345-x0a24208.web.app

**Comment by jessegduke** [comment]
@davidstanke - Take a look at my approach.  The `--edit-last` feature appears to have the following _"features"_ 

1) Updates the [last comment made by the user](https://cli.github.com/manual/gh_pr_comment).
2) Smart enough to know the difference in the `personal access tokens` used by Cloud Build vs. you "Dave" as a human.  
3) Will error on edit if no comment exists ([issue](https://github.com/cli/cli/issues/6790)).

Therefore, I would ask for your review/test...(each number addresses each item above. 
1) Does this approach look good to you.  
2) I would recommend as part of your testing, please add a comment below, then submit a content change on this branch to test this trigger.  It should update the comments above (with new time-stamp). 
3) I put an error check in the build: A hack, but seems to be viable for the short script.  

For all, I am open to other thoughts/approaches.

**Comment by davidstanke** [comment]
Oooh, REPO_FULL_NAME… that’s new! Nice. Lots of good stuff here and yes! The approach looks elegant and concise. Let’s see what happens when I push a new commit. One sec…

**Comment by davidstanke** [comment]
…looks like it posted a fresh comment. But, this is the first time that me-as-human am contributing on this PR. I’ll try pushing another change.

**Comment by jessegduke** [comment]
Odd (on both events I see above).  If I have time this weekend, I will revisit.  How did you create the Github token?  Behavior is diff from my other sandbox.

I will return to draft PR.

**Comment by davidstanke** [comment]
Hmm… I think it might not be quite there(?) Oddly, it seems to be quite happy to overwrite the comments I put in as a human, but then it doesn’t want to overwrite the comments made by the CI process.

**Comment by davidstanke** [comment]
So, yeah, the problem may well be the auth token, which (as you can see) is tied to my personal account and probably shouldn’t be. I’m always a bit confused about best practice for that. Can we change/improve how the CI is authed to GitHub? I’m happy to generate new credentials, if you can advise on the preferred method.

**Comment by jessegduke** [comment]
I want to see if we can leverage the [Google Cloud Build Github app](https://github.com/apps/google-cloud-build) (that we currently use for build triggers).  That looks to have 'read and write access' back to the repo. That would also remove the need for human, personal tokens.

**Comment by jessegduke** [comment]
One possibility is to create a [machine user github account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#personal-accounts) that would serve as the CI account. Specifically from docs:

```
Tip: Personal accounts are intended for humans, but you can create accounts to automate activity on 
GitHub. This type of account is called a machine user. For example, you can create a machine user 
account to automate continuous integration (CI) workflows.
```
This would grant finer grain permissions vs. Admin level that you personal have at the moment.

Give that some thought and give a yea or nay.

**Comment by davidstanke** [comment]
> One possibility is to create a [machine user github account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#personal-accounts) that would serve as the CI account.

Yep, that makes sense! And there's even (now) an obvious way to do it, which is to create the user with a *@dora.dev email identity. This was not obvious when it started but now it is. I'll make it happen.

**Comment by jessegduke** [comment]
Will wait for User Account to be created ( issue #379 )

**Comment by dora-machine-user** [comment]
Cloud Build time: Tue Sep 19 12:01:54 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr345-draft-z22djptg.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr345-vk0gbsu5.web.app

**Comment by jessegduke** [comment]
OK @davidstanke -- Take a look-see and let me know.  Right now, we should only have 1 (and only 1) entry by the CI build user (as seen above) with history of changes listed in the edit drop-down.

Please review approach and language in the write-back :).

Ready for review

**Review by davidstanke — APPROVED** [review]
Love it! Thank you for sticking with this one... it's been a long road but our DevEx is substantially better for it.

**Comment by davidstanke** [comment]
Okay, this is my new favorite thing. Thank you again, @jessegduke!
image

**Pull request merged**
