### PR TITLE
121 make a partial to process scss files and render link tags

### PR DESCRIPTION
**Pull request by jessegduke**

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Tue Oct 31 21:07:43 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr456-draft-h8ih9rl4.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr456-r43q4m0p.web.app

**Comment by jessegduke** [comment]
@davidstanke - We need **not** to try to merge this week, but if you have a desire and time, I have completed the following:

1. Added comments to [hugo/themes/dora/layouts/partials/link_styles.html](hugo/themes/dora/layouts/partials/link_styles.html)
2. Removed the "Options for the ToCSS pipe. However, documented how to implement in the future if needed.
3. a) Removed the range loop and b) removed from Markdown.  As a result, a few new Layout files for to defined the CSS needed for that Content.  Here is where your Hugo knowledge might recommend a diff. approach.
4. Removed the dictionary object allowing for easier Layout consumption (e.g.): 
` {{- partial "partials/link_styles" "scss/homepage.scss" -}} `

If you approve the approach, I will do a number of manual checks on styles while you are OOO, and we merge upon your return.

**Comment by davidstanke** [comment]
Jesse, this looks really good! Any reason we _can't_ merge it this week? I won't do it tonight, since I'm high on sugar, but I feel pretty confident we can proceed. Nice work!

**Comment by jessegduke** [comment]
No reasons at all.  I rechecked this morning, and all the styles appear to be working as expected.  I will remove from Draft, and feel free to approve and merge based upon your comfort level before vacation :) and sugar recovery from last night.

**Review by davidstanke — APPROVED** [review]
Merging! What a nice refactor. Thanks Jesse!

**Pull request merged**
