### PR TITLE
Display Quick Check legend vertically

### LINKED ISSUE #531: Display Quick Check legend vertically
Per [user request](https://github.com/dora-team/dora.dev/discussions/523#discussioncomment-8302239), format the legend vertically.

### PR DESCRIPTION
**Pull request by nathenharvey**
Fixes #531

Preview:
https://doradotdev-staging--pr713-drafts-off-dm2ccyln.web.app/quickcheck/?leadtime=5&deployfreq=4&changefailure=29&failurerecovery=4&v=2023&industry=all

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Fri Aug  9 03:23:02 UTC 2024
Preview this PR [with drafts on] at https://doradotdev-staging--pr713-drafts-on-smwdugc3.web.app
Preview this PR [with drafts off] at https://doradotdev-staging--pr713-drafts-off-dm2ccyln.web.app

**Comment by davidstanke** [comment]
Thanks for taking this on! I have suggestions, but if you disagree, then disregard:
image

**Review by davidstanke — CHANGES_REQUESTED** [review]
see screenshot w/ suggestions-- but if you disagree, I encourage you to disregard and force-merge... implementation looks good.

**Comment by nathenharvey** [comment]
good call!  I'll update and resubmit

**Review by davidstanke — APPROVED** [review]
LGTM - thanks for the revisions!

**Pull request merged**
