### PR TITLE
2024 sodr

### PR DESCRIPTION
**Pull request by nathenharvey**
Preview links:

* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/publications/
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/publications/errata
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/research/2024/
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/research/2024/dora-report/
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/research/2024/errata/
* https://doradotdev--pr785-drafts-off-dsqxecs0.web.app/brand-guidelines

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Thu Oct 17 13:19:55 UTC 2024
Preview this PR [with drafts on] at https://doradotdev--pr785-drafts-on-trctjxuv.web.app
Preview this PR [with drafts off] at https://doradotdev--pr785-drafts-off-dsqxecs0.web.app

**Review by davidstanke — APPROVED** [review]
Yay! Looks great. Approved (not merged).

**Comment by davidstanke** [comment]
> [rudimentarily aligning sponsor logos](https://github.com/dora-team/dora.dev/pull/785/commits/989a572d2298d25f7b778135aa0d9d5950d0b810)

If that gets too cumbersome, you might be able to use a `<grid class="border_none"` (like what's used above, but with more cells)... TBH, though, i don't remember the implementation of `<grid>` well enough to know if it will serve that purpose.

**Comment by nathenharvey** [comment]
> > [rudimentarily aligning sponsor logos](https://github.com/dora-team/dora.dev/pull/785/commits/989a572d2298d25f7b778135aa0d9d5950d0b810)
> 
> If that gets too cumbersome, you might be able to use a `<grid class="border_none"` (like what's used above, but with more cells)... TBH, though, i don't remember the implementation of `<grid>` well enough to know if it will serve that purpose.

yes, it's on my TODO list to leverage something a bit more sophisticated and `nbsp;`s

**Pull request merged**
