### PR TITLE
171-Activate-capabilities-and-update-menu

### LINKED ISSUE #171: Activate capabilities and update menu
Update menu link to point to `/devops-capabilities`, and change `draft` to false on all pages.

### PR DESCRIPTION
**Pull request by davidstanke**
This PR is based on #161. Merge that first

(Fixes #171)

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr172-a9mvytdm.web.app

**Comment by michelleirvine** [comment]
+1 to Amanda's comment.

Could have "Learn more -->" on a new line for each tile, not just the ones where it has an awkward line break

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr172-a9mvytdm.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr172-a9mvytdm.web.app

**Comment by davidstanke** [comment]
Good call -- updated! Take a look at https://draft-dora-dev--pr172-a9mvytdm.web.app/devops-capabilities/?update

**Comment by michelleirvine** [comment]
looks great!

**Review by michelleirvine — APPROVED** [review]

**Pull request merged**
