### PR TITLE
Cloud Functions - Added support for Unit and Continuous Integration Testing

### PR DESCRIPTION
**Pull request by jessegduke**
Starting on-line testing patterns for Cloud Functions via emulator
Based upon the following:
 - https://firebase.google.com/docs/functions/local-emulator
 - https://firebase.google.com/docs/functions/unit-testing
 - https://www.youtube.com/watch?v=VgQwlMtxbAw

### CODE REVIEW

**Comment by jessegduke** [comment]
Logging results show successful testing with the following:

```
Ran all test suites.
Time:        2.765 s
Snapshots:   0 total
Tests:       3 passed, 3 total
Test Suites: 1 passed, 1 total

    ✓ Function writes data in expected schema (152 ms)
    ✓ Function writes data and expect 1 result (302 ms)
    ✓ Can read from web form collection (1181 ms)
  EMAIL MONITOR
PASS test/emulation.test.js
```

**Comment by jessegduke** [comment]
@davidstanke - Can you take a close look at `ci/preview-infra.cloudbuild.yaml` at the `CI Testing` step to see if there is a smarter way (yet avoiding container maintenance).   

Testing is via the emulator (on-line and ephemeral).  This requires NodeJS, Java, and Firebase tools.  Lot of installs happening (which make me twitchy :) ).  Other ideas, please send my way.

I will keep in Draft PR, until you think this is directionally aligned.

**Comment by davidstanke** [comment]
> @davidstanke - Can you take a close look at `ci/preview-infra.cloudbuild.yaml` at the `CI Testing` step to see if there is a smarter way (yet avoiding container maintenance).
> 
> Testing is via the emulator (on-line and ephemeral). This requires NodeJS, Java, and Firebase tools. Lot of installs happening (which make me twitchy :) ). Other ideas, please send my way.
> 
> I will keep in Draft PR, until you think this is directionally aligned.

Hi @jessegduke! This is great work and well structured. I can see how, yes, it's getting a bit messy with all those tools. Yet it may be the right approach. A few questions, based on limited knowledge of this domain:

1. Why is Java necessary? Since you added it, I'm sure it's there for a reason, it's just not intuitive to me.
2. The testing step you added in CI runs Node commands. Could we run those in the `Node install` step instead?
  * (There's an argument to be made for wrapping _all_ of the steps into one big script, run in a ubuntu container [that is: move everything into step 0]; it's less elegant in terms of separation of actions but it would probably run faster, and is arguably easier to reason about. I'm not advocating that, just yet, but I think it's worth considering.)
3. What would happen if we didn't use the emulator, and instead ran this install and tests on the `staging` infra? Again, it's less elegant, but just as an idea to explore, I don't feel that it's essential to have isolated/ephemeral environments for this test. (Such is always conceptually superior, but if it adds time/complexity, I don't want to be dogmatic about it.)
4. [out of scope, but asking because it touches on this] How might we add tests for content etc.? I would like to have some validation on each PR that the site content is ~correct... this may be a completely different project than the tests you've added here, but I wanted to raise it just in case it impacts on this.

Let me know. Thank you!!!

**Comment by jessegduke** [comment]
> 

1. `Why is Java necessary?` - Firebase *emulator* is a java app.  More specifically, the *Firestore* emulator is a java process  [more details here](https://firebase.google.com/docs/emulator-suite/install_and_configure)

2. `The testing step you added in CI runs Node commands. Could we run those in the Node install step instead?` During the same build step, I need access to the java, node, and firebase *runtimes* :  Firebase emulator (java and firebase) will execute the Tests (Node/NPM).  If there is a better way to have access to all three runtimes, then yes.  However, I was under the impression (could be wrong) that when a new Build container is loaded, we loose access to the previous cloud build container image binaries and only keep the results of the derived artifacts (e.g., npm install assets).

3. `What would happen if we didn't use the emulator, and instead ran this install and tests on the staging infra? ` -- Very possible. I can try that.  My initial goal is that I wanted to be able to have a clean firestore db so that we could truly test and limit the *blast radius* for testing cloud functions, rules, and anything in the future.  I personally would choose this over time trade-offs, but that is from years of shooting myself in the foot 😃 .  I would recommend a 'test' container with all the testing tools to remove some of the build steps in the Test environment. 

4. `[out of scope, but asking because it touches on this] How might we add tests for content etc.?`. This is one reason why I started the emulator to be able to scale out future needs.  Now, `content` is another beast (IMO) since we need to think about multiple browsers, form-factors, versions, responsiveness etc.  It has been a few years, but I would need to review options.  If we don't leverage a SaaS offering, we need to consider headless browser implementations (e.g. Selenium or others).  This might drive the need for having a formal `dora-testing-container` to have everything managed in one container for testing.

Let me know if you'd like to talk thru some thoughts.... no ego here, happy to support however.

**Comment by jessegduke** [comment]
@davidstanke - Over the weekend, I will push new changes.  I added support for GCP Hosted Firebase (ie., no emulation), but I kept the emulator for local testing as an option (I like it for desktop testing without the need to push new Cloud Functions into Stage).  

I need to think thru securely access to the [App Engine default service account key](https://firebase.google.com/docs/functions/unit-testing#online-mode).  I'll research options since this would be executed in Cloud Build.

**Comment by jessegduke** [comment]
@davidstanke ... Seems like "version 2" of my attempts are better 😄 .  I added `functions/inquiry-monitor/README.md` to communicate approach to unit testing (via emulator) and CI Integration testing (on-line in stage).  

Take a look and let me know....  Happy to talk thru as needed.

**Comment by jessegduke** [comment]
@davidstanke - Out of draft and ready for review/merge.

**Review by davidstanke — APPROVED** [review]
LGTM -- really nice work; thank you @jessegduke !!!

**Pull request merged**
