### PR TITLE
Update broken link to an article on Wikipedia

### PR DESCRIPTION
**Pull request by mike-the-brain**
Before:

Screenshot 2023-11-23 at 22 25 22

After:

Screenshot 2023-11-23 at 22 25 11

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Fri Nov 24 16:06:17 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr477-draft-otdftm9t.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr477-mx8c6ghl.web.app

**Review by davidstanke — APPROVED** [review]
LGTM

**Comment by davidstanke** [comment]
@mike-the-brain Thank you so much for the fix! Deploying now. :)

**Pull request merged**
