### PR TITLE
Initial i18n skaffolding

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds some config for adding French pages (I'm using French in development, but our i18n launch will include ~8 languages), and a dropdown menu to navigate between them.

None of this will be visible on the prod site; it only displays in "Draft" environments.

For the time being, anything other than the capability catalog (and Core) is out of scope for i18n, but we hope to translate the entire site, as quickly as we're able.

### CODE REVIEW

**Comment by davidstanke** [comment]
Oh, and to be clear: the French pages don't actually have any French on them. Yet.

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr293-draft-m51phuo4.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr293-053rbeae.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr293-053rbeae.web.app

**Review by michelleirvine — APPROVED** [review]

**Pull request merged**
