### PR TITLE
Make Publications responsive-er

### PR DESCRIPTION
**Pull request by Steve-Fenton**
This helps to resolve issue #142 

1. The grid reduces to two columns at the "large" breakpoint
2. The images are set to 100%, so they take up the available width at intermediate sizes

Max screens
Three columns on extra-large sizes

Medium and large screens
Two columns on large and medium sizes

Small screens
One column on small screens

### CODE REVIEW

**Comment by Steve-Fenton** [comment]
Link to Issue #142

**Comment by Steve-Fenton** [comment]
@davidstanke I have one question about the intention for images. There is some limiting at the moment on the images, which results in them being smaller than the card and left-aligned...

Currently Live:
Images

My assumption is that these should fill the card, without being cropped. This assumption might be wrong, so let me know if you'd like the original behaviour or cover/cropping?

Assumption (as this works nicely at all different sizes):
image

**Comment by davidstanke** [comment]
> @davidstanke I have one question about the intention for images. There is some limiting at the moment on the images, which results in them being smaller than the card and left-aligned...

Aha -- yes, I think your intuition is right. Let's go with the full width. :)

**Comment by davidstanke** [comment]
...and thank you for jumping in on this! :)

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr230-aautg8yv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr230-aautg8yv.web.app

**Review by davidstanke — APPROVED** [review]
LGTM -- thank you @Steve-Fenton !

**Pull request merged**
