### PR TITLE
Contact Us Re-submission Fix for Issue #222

### PR DESCRIPTION
**Pull request by jessegduke**

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr311-draft-9tjq5ce6.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr311-tmtgy6nv.web.app

**Comment by jessegduke** [comment]
Ready for your review @davidstanke 

(Side NOTE: This is a good example on why #308 should be considered).  I feel like I am spamming the prod email :)

**Comment by davidstanke** [comment]
> This is a good example on why #308 should be considered

+1! In addition to the issue of flooding inboxes, it just _feels_ wrong. I got super confused testing it because I instinctively went to test on staging.dora.dev—but the change wasn't there!

Anyway, once I found it, it worked as promised. Thank you!

**Review by davidstanke — APPROVED** [review]
LGTM

**Pull request merged**
