### PR TITLE
Adds Korean version of 2022 report

### PR DESCRIPTION
**Pull request by nathenharvey**
The Korean version of the 2022 report is now available, too.

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Tue Oct 10 15:51:18 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr417-draft-f6rpdkqs.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr417-5pzz66sh.web.app

**Comment by nathenharvey** [comment]
https://doradotdev-staging--pr417-5pzz66sh.web.app/research/2022/dora-report/

**Review by davidstanke — APPROVED** [review]
LGTM

**Comment by nathenharvey** [comment]
addresses #74

**Pull request merged**
