### PR TITLE
In the SCSS version

### PR DESCRIPTION
**Pull request by Aneal07**
I've defined variables for recurring values like the font stack and shadows and utilized nesting to group-related styles.
Created mixins and used the @include directive to include the mixins.
let me know if I have to add or change anything.
thanks.

### CODE REVIEW

**Comment by davidstanke** [comment]
Hi @Aneal07! I thought this looked promising... any particular reason you closed it? Interested in reopening it?

**Comment by Aneal07** [comment]
I thought you weren't interested. I'm reopening it again Let me know if anything needs to be done. Thanks.

**Comment by davidstanke** [comment]
Hey @Aneal07 -- I'm totally interested! (And apologies for my slow response times recently!) ... this looks great but I'm getting a build error on CI:

`Error: error building site: TOCSS: failed to transform "core/dora-core-model.scss" (text/x-scss): "/workspace/hugo/assets/core/dora-core-model.scss:30:18": no mixin named gearAnimation`

...does it work on your machine? If so, what version of Hugo are you using? The CI builder uses `v0.114.1 extended`

**Comment by davidstanke** [comment]
Odd... I'm still seeing the same problem (on my local and in the CI build). Is it working in your development environment?

**Pull request closed without merging**
