### PR TITLE
2022 localized

### PR DESCRIPTION
**Pull request by nathenharvey**
Adds the localized versions of the 2022 report with links on the report's home page.

### CODE REVIEW

**Comment by nathenharvey** [comment]
This page might work better as a grid with two columns, the cover image in the left column and the list of clickable langues in the right column.

**Comment by dora-machine-user** [comment]
Cloud Build time: Tue Oct 10 02:33:57 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr416-draft-4efc3yxv.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr416-cfnsw57n.web.app

**Comment by nathenharvey** [comment]
partially addresses #74

**Comment by nathenharvey** [comment]
Preview - https://doradotdev-staging--pr416-cfnsw57n.web.app/research/2022/dora-report/

**Review by davidstanke — APPROVED** [review]
Yup

**Pull request merged**
