### PR TITLE
Remove survey CTAs  (Fixes #270)

### LINKED ISSUE #270: Remove survey CTAs
When the survey closes, remove the yellow snipe from the page templates, and update the content of dora.dev/survey

### PR DESCRIPTION
**Pull request by davidstanke**
_DO NOT MERGE until the survey has closed!_

This PR removes the survey banner from all pages, and updates the content of `/survey`.

(Note that when we publish SODR 2023, we should update the stats on this page, but for now we can stick with the c. 2022 numbers)

Fixes #270

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr271-jdt2eu04.web.app

**Review by nathenharvey — APPROVED** [review]
Might benefit from some more globally inclusive language for the target release of the 2023 report, e.g., "the fourth quarter"

**Comment by davidstanke** [comment]
Ah... good call. I should be able to make that change later today.

**Comment by nathenharvey** [comment]
Don't worry about making the change...I can do a separate PR with the update, enjoy your vacation!

**Pull request merged**
