### PR TITLE
Issue 370 - Correct 404s for Documentation quality page links

### PR DESCRIPTION
**Pull request by jessegduke**

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr371-draft-ycdlqkdb.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr371-v21qr95m.web.app

**Comment by jessegduke** [comment]
@davidstanke - Comparison under "Measuring" and "The impact... 

Dora Prod (404 error) - https://dora.dev/devops-capabilities/process/documentation-quality/
This PR - https://doradotdev--pr371-draft-ycdlqkdb.web.app/devops-capabilities/process/documentation-quality/

**Review by davidstanke — APPROVED** [review]
D'oh! That looks like a Stanke-fail. Thanks so much for catching and fixing it!

**Pull request merged**
