### PR TITLE
document staging CI  (Fixes #277)

### LINKED ISSUE #277: Deploy proposed infra changes to `staging`
(Follow-up from #225)

There is now a staging.dora.dev server. When a PR is opened with changes outside of `/hugo/content/`, run the Cloud Build config `/ci/preview-infra.cloudbuild.yaml`, to deploy those changes to staging.dora.dev

(Current status: all the config is implemented, but there's a missing permission.)

### PR DESCRIPTION
**Pull request by davidstanke**
This PR updates the documentation in `/ci` to reflect updates to CI. (Due to the dodgy nature of testing CI, I went ahead and merged all the relevant changes. So everything described in this README should actually already be in effect.)

Fixes #277

### CODE REVIEW

**Comment by davidstanke** [comment]
Hey @jessegduke -- PTAL. If you feel there are improvements to be made, please let me know on this PR, or—if they're not blocking—open separate issues for them. (E.g. I opened #290 ) Thanks!

**Comment by jessegduke** [comment]
@davidstanke - I believe the approach will work just fine.  I took a diff. path in my sandbox, but I think this is more modular and better for future flexibility.  I will continue to review over the weekend. 

While you wait :) a few thoughts for dialog before I approve to help me to understand correctly.  

1. (non-blocking) `README.md`  For this file/PR as a document change, I did not consider blocking.   However, there is a type-o.  I believe the correct domain for staging is`.dev` (?)  I see `.com` (line 4).  While not "blocking" functionality, if you need to change in others, we can.  Otherwise, I will open a new issue as requested.
--- 
The following is outside this "PR", but files are implicated in your approach.

2. (blocking) In file `preview-content.cloudbuild.yaml`: I don't see correct `firebase-config` to auth to the staging FS Database.  I believe you will need a diff. `firebase-config` for stage Firestore authentication.  In my sandbox, I addressed with the following step prior to the  hugo build:
    `cp hugo/static/js/firebase-config.${PROJECT_ID}.js /workspace/hugo/static/js/firebase-config.js` where `firebase-config.${PROJECT_ID}.js` is a new file(s) and populated with the correct values for each Firestore DB

3. (non-blocking) For file `preview-infra.cloudbuild.yaml`, is Hugo needed w/in step 1: 'ubuntu'?
    Could be simplified with: `firebase deploy --non-interactive --project=${PROJECT_ID} --only functions,firestore,remoteconfig`.  See note 4 below on additional flag.  We can mark this as a new separate issue if you agree.

4. (blocking) For `preview-infra.cloudbuild.yaml` and `cloudbuild.yaml`:  I am pretty sure you will need to add the `--non-interactive` flag to the `firebase deploy` commands.  I have had cli interactive prompts in the past for Infra related deployments.
    
    NOTE: I believe I have had to use the `--force` flag if the extension password is modified.  Let's not for now, but something to monitor.

A lot of thoughts, let me know if you want to verbally discuss and we can capture in docs any thoughts/decisions

**Comment by davidstanke** [comment]
@jessegduke thank you for thoughtful review! Responses inline...
 
> 1. (non-blocking) `README.md`  For this file/PR as a document change, I did not consider blocking.   However, there is a type-o.  I believe the correct domain for staging is`.dev` (?)  I see `.com` (line 4).  While not "blocking" functionality, if you need to change in others, we can.  Otherwise, I will open a new issue as requested.

D'oh! Fixed.

> The following is outside this "PR", but files are implicated in your approach.
> 
> 2. (blocking) In file `preview-content.cloudbuild.yaml`: I don't see correct `firebase-config` to auth to the staging FS Database.  I believe you will need a diff. `firebase-config` for stage Firestore authentication.  In my sandbox, I addressed with the following step prior to the  hugo build:
>    `cp hugo/static/js/firebase-config.${PROJECT_ID}.js /workspace/hugo/static/js/firebase-config.js` where `firebase-config.${PROJECT_ID}.js` is a new file(s) and populated with the correct values for each Firestore DB

That makes sense! (See below)

> 3. (non-blocking) For file `preview-infra.cloudbuild.yaml`, is Hugo needed w/in step 1: 'ubuntu'?
>    Could be simplified with: `firebase deploy --non-interactive --project=${PROJECT_ID} --only functions,firestore,remoteconfig`.  See note 4 below on additional flag.  We can mark this as a new separate issue if you agree.

This is working as intended... but I debated it as well: _should the infra preview *also* preview content?_ ...and I ended up feeling that, yes, we should build and deploy the Hugo content as part of the infra preview. Because we can't ever be completely sure what kind of interactions might happen between the infra config and the latest content. So I'd like the staging server to be a complete reflection of whatever is contained in the PR that is deployed to it. This means the content on staging will flap around based on whatever's in the most recent PR. I'm okay with that, since that's already what we're doing with the infra. (AFAIK, there's no way to fully virtualize Firebase as part of a preview, so instead, we're using `staging` as a shared sandbox. May as well go all the way with that.) If you disagree, let's discuss!

> 4. (blocking) For `preview-infra.cloudbuild.yaml` and `cloudbuild.yaml`:  I am pretty sure you will need to add the `--non-interactive` flag to the `firebase deploy` commands.  I have had cli interactive prompts in the past for Infra related deployments.
>    NOTE: I believe I have had to use the `--force` flag if the extension password is modified.  Let's not for now, but something to monitor.

Aha! So, between no. 2 and no. 4, this may explain why I've had trouble updating the extension via CI (and it may be that updates to prod would fail if attempted). Your expertise is much appreciated here! 😃 Do you have time to help fix these gaps? (I feel this is _important_ but not _urgent_, so it doesn't have to be immediate.) If so: **can you open a PR with those changes?** In the process, you're welcome to do _whatever you like_ with `staging`. The purpose of that server is to help us safely evolve our infra, so don't hesitate at all to mess it up along the way.

**Comment by jessegduke** [comment]
Let's do it!  I will approve this PR, and open a new one for the remaining items we chatted above!

**Review by jessegduke — APPROVED** [review]

**Comment by davidstanke** [comment]
Thank you!

**Pull request merged**
