### PR TITLE
optional slash on capabilities redirect

### PR DESCRIPTION
**Pull request by davidstanke**

### CODE REVIEW

**Comment by davidstanke** [comment]
After #201 was merged (thank you!), I realized that it would be convenienter if we could use the short URL with or without the trailing slash.

With some tinkering, I found that the syntax in this PR works in either case (I think because of [this(https://firebase.google.com/docs/hosting/full-config#control_trailing_slashes)).

**Comment by davidstanke** [comment]
@jessegduke, can you confirm? Thanks!

**Comment by jessegduke** [comment]
Confirmed.

**Review by jessegduke — APPROVED** [review]
Approved

**Comment by davidstanke** [comment]
Thank you, @jessegduke !

**Pull request merged**
