### PR TITLE
add eyechart pages

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds "eyechart" pages, for... uh, no particular reason.

Seriously, don't worry about it. Nothing to see here.

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr373-draft-byu41c2d.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr373-phxm5h07.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr373-draft-byu41c2d.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr373-phxm5h07.web.app

**Review by swansama — APPROVED** [review]
LGTM!  Love it :)

**Pull request merged**
