### PR TITLE
181-Interactive-predictive-model

### LINKED ISSUE #181: Interactive predictive model
Feedback from the community, the interactive predictive model has not been migrated.

"The site seems to be missing the interactive predictive model. Can you put a link back to this?" - Scott Prugh

Investigate adding to dora.dev site.

### PR DESCRIPTION
**Pull request by davidstanke**
This PR replaces the static BFD image on `/research/` with a port of the dynamic BFD from devops-research.com -- the styles and scripts have been refactored to fit within dora-dev, so there may be some minor UI deviations. However, the functionality should be intact, so reviewers should be on the lookout for any functional regressions.

(Fixes #181)

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by nathenharvey** [comment]
the windows that pop-up when clicking on a node are not dynamically sized and when they take up more than the available screen, they are not scrollable.  This is OK if we have a solution that can quickly follow but otherwise I'd prefer we take the time to fix this.

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr187-qmjcjjjv.web.app

**Review by nathenharvey — APPROVED** [review]
:shipit:

**Pull request merged**
