### PR TITLE
Add redirects from legacy urls  (Fixes #2)

### LINKED ISSUE #2: Add redirects from legacy urls
AIUI, best practice is generally to avoid URLs with ".html" in them. So we'll use paths like `/research/`, rather than `/research.html`

...but existing links go to `/research.html` so we'll need to redirect those. Redirects can be added to `firebase.json`

### PR DESCRIPTION
**Pull request by davidstanke**
Fixes #2

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr152-ev4osp8p.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr152-ev4osp8p.web.app

**Comment by nathenharvey** [comment]
LGTM.  I would expect https://draft-dora-dev--pr152-ev4osp8p.web.app/research.html#capabilities to link to https://draft-dora-dev--pr152-ev4osp8p.web.app/capabilities/ but that can either be a separate issue or an expectation that I need to get over.

**Review by nathenharvey — APPROVED** [review]

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr152-ev4osp8p.web.app

**Comment by davidstanke** [comment]
> LGTM.  I would expect https://draft-dora-dev--pr152-ev4osp8p.web.app/research.html#capabilities to link to https://draft-dora-dev--pr152-ev4osp8p.web.app/capabilities/ but that can either be a separate issue or an expectation that I need to get over.

Your expectations make sense to me, but unfortunately not to the internet... browsers don't send anchor links to the server, so we can't distinguish between research.html and research.html#capabilities :-(

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr152-ev4osp8p.web.app

**Pull request merged**
