### PR TITLE
Update the core 2.0 pdfs

### PR DESCRIPTION
**Pull request by nathenharvey**
attempting to improve the rendering

CleanShot 2024-12-09 at 12 02 15

Preview:

* Detail - [preveiw](https://doradotdev--pr838-drafts-off-wlgoqeuy.web.app/research/dora-core-v2.0.0-detail.pdf) vs. [production](https://dora.dev/research/dora-core-v2.0.0-detail.pdf)
* Summary - [preview](https://doradotdev--pr838-drafts-off-wlgoqeuy.web.app/research/dora-core-v2.0.0-summary.pdf) vs. [production](https://dora.dev/research/dora-core-v2.0.0-summary.pdf)

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Sun Dec  8 21:52:43 UTC 2024
Preview this PR [with drafts on] at https://doradotdev--pr838-drafts-on-jv528u84.web.app
Preview this PR [with drafts off] at https://doradotdev--pr838-drafts-off-wlgoqeuy.web.app

**Review by ericmaxwell-google — APPROVED** [review]
LGTM

**Pull request merged**
