### PR TITLE
Make capabilities index responsive  (Fixes #165)

### LINKED ISSUE #165: Make capabilities index responsive
`/devops-capabilities/`

### PR DESCRIPTION
**Pull request by davidstanke**
This PR makes the index of the capabilities page (/devops-capabilities/) responsive, by reducing to two columns on medium-width screens, and one column on narrow screens.

Fixes #165

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr178-2dw4jatm.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr178-2dw4jatm.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr178-2dw4jatm.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr178-2dw4jatm.web.app

**Review by swansama — APPROVED** [review]
LGTM

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr178-2dw4jatm.web.app

**Pull request merged**
