### PR TITLE
Adds the 2023 report to dora.dev

### PR DESCRIPTION
**Pull request by nathenharvey**
In preparation for releasing the 2024 report.

Preview:

* https://doradotdev--pr784-drafts-off-trg0pa9w.web.app/research/2023/dora-report/

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Fri Oct 11 16:29:41 UTC 2024
Preview this PR [with drafts on] at https://doradotdev--pr784-drafts-on-1sfm1alu.web.app
Preview this PR [with drafts off] at https://doradotdev--pr784-drafts-off-trg0pa9w.web.app

**Comment by nathenharvey** [comment]
this is ready for review but not for merging. we will schedule the merge and deploy just before the launch of the 2024 report.

**Review by davidstanke — APPROVED** [review]
LGTM

**Pull request merged**
