### PR TITLE
295 add functionality for fb auth deploy in staging

### PR DESCRIPTION
**Pull request by jessegduke**
@davidstanke - Let's try again.  

Cloudbuild would now support CI with access to the new Staging Firebase DB in-line with the deployment strategy you developed in #277.

Notable change:  The `hugo/static/js/firebase-config.js` now defaults to the staging environment.  This will help ensure desktop development does not accidentally write to prod database.  However, if you disagree, we can revert

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr300-draft-8uu4rh5j.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr300-e1slqp30.web.app

**Comment by jessegduke** [comment]
Firebase is not installing correctly.  converted back to Draft PR

**Comment by davidstanke** [comment]
```
Notable change: The hugo/static/js/firebase-config.js now defaults to the staging environment. This will help ensure desktop development does not accidentally write to prod database. However, if you disagree, we can revert
```

Makes sense -- I like! Sounds like you're getting close. If you'd like to pair-program/talk it through, you're welcome to grab some time on my calendar. Otherwise, I await your revisions eagerly, but not impatiently.

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr300-draft-8uu4rh5j.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr300-e1slqp30.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr300-draft-8uu4rh5j.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr300-e1slqp30.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr300-e1slqp30.web.app

**Comment by jessegduke** [comment]
@davidstanke - FINALLY :) ... All ready for review.

**Review by davidstanke — APPROVED** [review]
Excellent work, @jessegduke ! Thank you; LGTM.

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr300-draft-8uu4rh5j.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr300-e1slqp30.web.app

**Pull request merged**
