### PR TITLE
add ADRs for Firebase Hosting, Firestore

### LINKED ISSUE #191: Document use of Firebase

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds Architecture Decision Records describing two technologies in use for dora.dev

Fixes #191

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Review by sapientcoffee — APPROVED** [review]
lgtm

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr193-ws2e63h8.web.app

**Pull request merged**
