### PR TITLE
Add configuration for multilangual support

### PR DESCRIPTION
**Pull request by Winael**

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr326-draft-gclz7ijx.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr326-c9wnu6pk.web.app

**Comment by davidstanke** [comment]
@Winael I haven't forgotten this conversation! But I want to establish some guidelines for how we will maintain translations going forward, before we go too far down the road of implementation. So I'm drafting something (coming soon!) that I'd like your feedback on, and then we can push this forward.

**Comment by Winael** [comment]
Hi @davidstanke 

Don't worry, this PR was just to push a working configuration for multilangual instead of sending it by email.

Regards

**Comment by davidstanke** [comment]
Ah, got it -- in that spirit, I'm converting it to a Draft PR. Thanks!

**Comment by Winael** [comment]
Hi Dave,

Sorry to learn that you didn't find a solution, but hopefully, with the
progress on GenAI maybe in-browser translation will be accurate enough to
not have effort to do on text translation. And if the source of image are
available maybe it will be possible to show a translated image if existed
based on browser langage.

This PR can be closed :)

Le jeu. 21 mars 2024, 17:54, Dave Stanke ***@***.***> a
écrit :

**Pull request closed without merging**
