### PR TITLE
Fix: Sentence Case for Capabilities

### PR DESCRIPTION
**Pull request by mukteshkrmishra**
√ Fix for https://github.com/dora-team/dora.dev/issues/168

Added sentence case for each capability in the tile. 

Screenshot 2023-04-10 at 6 18 47 PM

**Steps to Test:**

- From the root directory pls run `hugo serve -D -s hugo --disableFastRender --verbose;`
- Check the changes at `http://localhost:1313/resources/`

### CODE REVIEW

**Comment by mukteshkrmishra** [comment]
@davidstanke : pls review

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr206-wtw7cndi.web.app

**Review by davidstanke — APPROVED** [review]
Looks great! (I love how Hugo makes it so the changes propagate to all of the places they appear... It's like a database, but it's stored in the form of the content files themselves.) thank you!

**Pull request merged**
