### PR TITLE
Add anchor link icons to headings

### LINKED ISSUE #240: Add anchor links to FAQ
I wanted to link directly to an item in the FAQ but could only link to the page URL (`/faq`).

Let's make it so we can send folks directly to specific topics. The anchor links should automagically reveal themselves, like they do in, for example, [GCP docs](https://cloud.google.com/compute/docs/create-linux-vm-instance)

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds a `partial` which decorates any heading that has an `id` element with a popup icon allowing users to easily copy a link to that heading. Details can be found in [this ADR](https://github.com/dora-team/dora.dev/pull/451/files#diff-1c6de5d88d6565792a57cecbe7930adaef0f63207e62c1624818768ccc598c30) 

The effect can be seen on this page: https://doradotdev-staging--pr451-draft-00jpulvn.web.app/faq/

Fixes #240

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Cloud Build time: Fri Oct 27 20:37:07 UTC 2023
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr451-draft-00jpulvn.web.app
Preview this PR [published content only] at https://doradotdev-staging--pr451-exyrdtd0.web.app

**Comment by davidstanke** [comment]
Hey @jessegduke! I'd love to get your feedback on this implementation... I haven't really been good about writing ADRs, but I did [one for this feature](https://github.com/dora-team/dora.dev/pull/451/files#diff-1c6de5d88d6565792a57cecbe7930adaef0f63207e62c1624818768ccc598c30) so you can follow my rationale. WDYT? Reasonable? Not so much?

**Review by jessegduke — APPROVED** [review]
I like the approach.  

Interestingly, maybe for some unexpected confirmation.  As I was working on another project (similar to `ask-dora`) which had a mix of Hugo and this very template - with a client/sever-side API interaction, I needed a similar outcome.  I found my way to vanilla JS to build the content anchors dynamically from the server-side response. 

In short, your ADR documented the same conclusion. Albeit, your approach is more elegant :)

**Comment by davidstanke** [comment]
Sweet, thanks for the quick review! I'm curious to check out your solution to the same problem, and perhaps it's time (after I get back from my vacay!) to extract the theme to its own repo, and reference it "properly" from these two sites that leverage it.

Deploying now. 🚀

**Pull request merged**
