### PR TITLE
Interactive-core

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds experimental/preliminary support for interactivity on the Core Model diagram. The content here has the `draft` flag set to `true`, so it won't render on the prod site, only in draft contexts (including the preview link, below). This is an artificial, small version of the model with only 4 entities, but it does have interactivity in the form of modal popups; after I've figured out the javascript and publishing pipeline bits, I'll render the full model.

For now, I'd like to merge in this WIP to the repo while continuing to develop it.

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr304-draft-ai7yank0.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr304-njlyaolz.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr304-draft-ai7yank0.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr304-njlyaolz.web.app

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr304-draft-ai7yank0.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr304-njlyaolz.web.app

**Review by swansama — APPROVED** [review]
LGTM - I like the boxes - will be interested to see how it looks when all of the core capabilities are included.

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr304-njlyaolz.web.app

**Pull request merged**
