### PR TITLE
Add "report an error" option to "Contact Us" form

### LINKED ISSUE #378: Add "report an error" option to the Contact Us form
(prerequisite for #375)

### PR DESCRIPTION
**Pull request by davidstanke**
This PR adds <select> options to the contact us form allowing users to report errors in specific publications. Valid errors will (eventually) be published to the site, as per #375.

Fixes #378

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr380-draft-wkwgug3k.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr380-bllgog8u.web.app

**Review by jessegduke — COMMENTED** [review]
The form looks good.  I could not test in Stage Firestore because the content preview is built and writing data to production Firestore ( issue #308  ). 

Test messages were sent to prod DB and I validated write was accurate.  You should have received emails if you wish to validate email content style.

Looks good from my view, if you can do final acknowledgement based upon this insight I will Approve.

**Comment by davidstanke** [comment]
Yep previews look good

**Review by jessegduke — APPROVED** [review]

**Pull request merged**
