### PR TITLE
tabs v2

### LINKED ISSUE #54: auto-hide inactive tabs in tab_navigation widget
```
<!-- TODO: auto-hide inactive tabs in this module -->
```

https://github.com/dora-team/dora.dev/blob/089cf17a7a71b72094245edec74fad4c06d178e5/hugo/layouts/shortcodes/tab_navigation.html#L2

### LINKED ISSUE #112: Reflect tab selections in URL
In `tab_navigation`: when a tab is selected, update the URL to indicate which tab is selected. And, on page load, if that parameter is present, automatically switch to the tab.

This will make it so a pasted URL will appear the same as when it was copied..

### PR DESCRIPTION
**Pull request by davidstanke**
This PR is a refactor of the tab navigation partial, using alpinejs to reduce the amount of js needed. It also adds the functionality of tab persistence: selected tabs are persisted to the URL, so if a user copies a link and shares it to a friend, the recipient's browser will open the same tabs that the sender saw.

Fixes #54; fixes #112

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr246-rlbjllnu.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr246-8kyradj3.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr246-8kyradj3.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr246-8kyradj3.web.app

**Review by jessegduke — APPROVED** [review]
Looks great!

**Comment by davidstanke** [comment]
Thank you, @jessegduke !

**Pull request merged**
