### PR TITLE
Refactor "help me prioritize" using Alpine

### LINKED ISSUE #247: Refactor prioritization exercise to use alpinejs
The prioritization exercise is all about showing/hiding elements... can we refactor to use alpinejs?

We may need to use some this to achieve the _scrolling into view_ effect: https://alpinejs.dev/directives/transition

### LINKED ISSUE #252: Support offline development
Most of our hugo/html/js work ought to be doable in a pure-local loop, without an internet connection. (Firebase emulators work offline, too, but some parts of the firebase implementation require being connected, even for local dev, and that's a much less frequent activity, so it's not a priority.)

Here are a couple small things we can do to support offline work:

- [x] vendor alpine into the repo and refer to it by local path
- [x] load google tag manager only in prod

### PR DESCRIPTION
**Pull request by davidstanke**
This PR is a refactor of the "help me prioritize" exercise to use alpine, which reduces code and will, I hope, make it more maintainable.

(FYI, the animation for moving between steps is now the standard alpine transition, rather than a custom slider effect. IMHO, it feels pretty much the same, and will be much more maintainable—that slider implementation was fragile.)

Fixes #247  (Also fixes #252)

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr250-kz7txbto.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr250-kz7txbto.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr250-kz7txbto.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr250-kz7txbto.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr250-kz7txbto.web.app

**Review by jessegduke — APPROVED** [review]
Functionality looks on par with previous efforts.

**Comment by davidstanke** [comment]
Thanks for the review!

**Pull request merged**
