### PR TITLE
56 notify on new contact form submission

### PR DESCRIPTION
**Pull request by jessegduke**
***Draft*** request only to confirm no impact to existing CI and Pull request CD efforts/design

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr223-lqfyq3p7.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr223-lqfyq3p7.web.app

**Comment by jessegduke** [comment]
@davidstanke - Let me know (Monday or later is fine), if you want to merge this into MAIN.  

This PR staged all the platform changes in MAIN, but does not affect the UI functionality.  The only effective change to the Web UI is externalizing the FB Config into a JS file. 

**Summary of Changes:**
- Two files changes in `hugo` directory: Externalizing the FB Config into a JS file
- `firebase.json` - Whitespace from my editor.  
- `gitignore` - added valued to exclude *local dev files
- `./platform` directory: Staged functionality to enable, Functions, Extensions, Firestore Rules, Remote Config
- `README.md` - Updated with guidance for Platform development

After this PR, we need to get SMTP user/password and update the Extension config with values.  At that point, we can implement a deployment process.

Concern: If we issue PRs against anything in the `./platform' - I assume it will issue new CI/CD for WebUI.  Not sure of the value in that.

**Comment by davidstanke** [comment]
@jessegduke this looks excellent! I'm ready to give it a proper review... if you're ready, **click the "Ready for review" button**, to take it out of draft mode.

`Concern: If we issue PRs against anything in the './platform' - I assume it will issue new CI/CD for WebUI. Not sure of the value in that.`
...yep, that's worth raising, but IMHO not something that should slow us down at this point (CI/CD remains fast and low-cost, so I'd rather err on the side of running it when we didn't need to, than failing to run it when we should... but we can certainly consider adding file pattern filters in Cloud Build to fine-tune what gets built based on what source is changed.)

**Comment by jessegduke** [comment]
Refactoring directory structure as we discussed.  Closing this PR with Comment.

**Pull request closed without merging**
