### PR TITLE
Download attributes

### PR DESCRIPTION
**Pull request by Aneal07**

### CODE REVIEW

**Comment by davidstanke** [comment]
Preview this PR [including DRAFT content] at https://doradotdev--pr357-draft-r51qcq9g.web.app

**Comment by davidstanke** [comment]
Preview this PR [published content only] at https://doradotdev--pr357-estccc9l.web.app

**Comment by davidstanke** [comment]
Perfect! (I didn't realize it was that simple... glad you knew it.) Thank you, @Aneal07 !

**Review by davidstanke — APPROVED** [review]

**Comment by Aneal07** [comment]
Glad I could help.

**Pull request merged**
