### PR TITLE
Fix: Adding Images to each Resource

### PR DESCRIPTION
**Pull request by mukteshkrmishra**
√ Fix for https://github.com/dora-team/dora.dev/issues/101
Added images for each resource. 

Screenshot 2023-04-10 at 5 14 14 PM

**Steps to Test:** 

- From the root directory pls run `hugo serve -D -s hugo --disableFastRender --verbose;`
- Check the changes at [http://localhost:1313/resources/](http://localhost:1313/resources/)

### CODE REVIEW

**Comment by mukteshkrmishra** [comment]
@davidstanke : pls review

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr205-5mnywsyy.web.app

**Comment by davidstanke** [comment]
Nice! A few requests @mukteshkrmishra:

- [ ] Let’s remove the words “four keys” from the four keys logo; it’s redundant
- [ ] Move the title (and subtitle, if present) for each item down below the image
- [ ] Add some vertical spacing between each Resource and the next. 

Thanks!

**Comment by mukteshkrmishra** [comment]
@davidstanke : changed layout based on the feedback. Pls review. Screenshot 2023-04-10 at 5 42 17 PM

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr205-5mnywsyy.web.app

**Review by davidstanke — APPROVED** [review]
Looks great — thank you!

**Pull request merged**
