### PR TITLE
Remove "archives" from research URLs  (Fixes #389)

### LINKED ISSUE #389: Remove "archives" from research URLs
In URLs like `https://dora.dev/research/archives/2022/`, the token "archives" is not necessary (while that content is indeed from the past, it's not, say, _deprecated_). Let's remove that token, so the URL pattern becomes:

`/research/<year>/`

Also, add redirects from the old pattern to the new one.

### PR DESCRIPTION
**Pull request by davidstanke**
- move individual files from `/research/archives` into content bundles within `/research/` named after reseach year
- update template files
- add firebase redirect rule to handle legacy URLs
- the `/research/archives/` section page now throws a 404 (that's okay; traffic to that page was negligible and it's not worth maintaining a redirect for it)

Fixes #389

(Prereq for #390)

### CODE REVIEW

**Comment by dora-machine-user** [comment]
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr391-draft-obdhdqw1.web.app

**Comment by dora-machine-user** [comment]
Preview this PR [published content only] at https://doradotdev-staging--pr391-n9uyx5m7.web.app

**Comment by jessegduke** [comment]
@davidstanke - One requested change and a couple of 'nits' that you might want to fold in.

Let me know your preferences and I can approve thereafter.

_____

**Requested Change**
hugo/content/research/_index.md - Remainder reference to giving 404. Either remove to correct to [insert Dave's choice]

```html
DORA is the [longest running](/research/archives/) 
```


**Typos**
hugo/content/research/2018/_index.md
    indepently --> independently

hugo/content/research/2022/_index.md
developmend --> development

hugo/content/devops-capabilities/process/streamlining-change-approval
implementati --> implementation

**Nit**
Could we remove? hugo/layouts/research_archives/section.html.BAK

**Comment by dora-machine-user** [comment]
Preview this PR [including DRAFT content] at https://doradotdev-staging--pr391-draft-obdhdqw1.web.app

**Comment by dora-machine-user** [comment]
Preview this PR [published content only] at https://doradotdev-staging--pr391-n9uyx5m7.web.app

**Comment by davidstanke** [comment]
@jessegduke thanks for catching those! Good eyes. They're all fixed, now.

**Review by jessegduke — APPROVED** [review]
LGTM!

**Pull request merged**
