### PR TITLE
fix typo  (Fixes #200)

### LINKED ISSUE #200: Minor Type-o in FAQ
Minor Type-o in [FAQ](https://dora.dev/faq/).  

`hugo/content/faq/_index.md`

image

### PR DESCRIPTION
**Pull request by davidstanke**
fix #200

### CODE REVIEW

**Comment by davidstanke** [comment]
Nice catch, @jessegduke!

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr204-zgf2gw0h.web.app

**Review by jessegduke — APPROVED** [review]

**Comment by jessegduke** [comment]
LGTM

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr204-zgf2gw0h.web.app

**Comment by davidstanke** [comment]
Preview this PR at https://draft-dora-dev--pr204-zgf2gw0h.web.app

**Pull request merged**
